### ISSUE TITLE
Global section is not picked up.

### ISSUE THREAD

**Issue by zhenyun** [linkedin/naarad#277]
The `ts_start` and `ts_end` defined in Global Section are not picked up. 

e.g.,   
http://zzhuang-ld1/naarad.test/

**Comment by zhenyun** [comment]
the issue persists...

**Comment by feng-tao** [comment]
hi, I root cause and fix this bug. The fix works on my example config. Is there anyone could give a try on my fix?

**Comment by richardhsu** [comment]
Please push your changes to a branch on your forked repository, that way one of us can pull the changes and test on our system as well with our own configurations and/or logs.

Might also be helpful to paste the config example you used and what log you used.

**Comment by feng-tao** [comment]
push the fix to my local branch(https://github.com/feng-tao/naarad/tree/bug_227)

**Comment by richardhsu** [comment]
Pull request #327 has been merged and fixes this.
