### ISSUE TITLE
"Max" metric value should be calculated before "aggregation"

### ISSUE THREAD

**Issue by zhenyun** [linkedin/naarad#282]
I just found that the "max" value is calculated AFTER per-second aggregation. 
For instance, 
00:00:01.2, 50
00:00:01.4, 0
The max value should be 50; while currently due to aggregation, the max is 25. 
Also:  currently the plotted values (e.g., WORKLOAD metric) are also aggregated values.  
We should allow the user to do with/without aggregation. (e.g., in config file).

**Comment by feng-tao** [comment]
I could not locate an example log file with sub-seconds timeseries samples. Do you guys have an input file which could reproduce this issue?

**Comment by zhenyun** [comment]
I will find one for you tomorrow.
Or, you can "make up" one.

zen
________________________________

**Comment by feng-tao** [comment]
I verify this bug with example sar config as well as zen's application csv file. I think this issue no longer exists. We could close this bug.
