### ISSUE TITLE
Aggregation should be disabled by default

### ISSUE THREAD

**Issue by zhenyun** [linkedin/naarad#308]
The per-second aggregation should be disabled by default. 
With that aggregation, even though the max latency is actually 98 ms, the processed csv file only shows 57 ms (averaged value in each second).

The control should be in `metric.py`.

Users should be able to enable it in configure file.

**Comment by feng-tao** [comment]
Hi Zen, I dont think this issue also persists. I verify with your application log, which the max/min value series does not get affected by the aggregation. Please advise.

**Comment by zhenyun** [comment]
Then just close it.
thanks.
zen
________________________________
