### ISSUE TITLE
luminol should not be required by default

### ISSUE THREAD

**Issue by zhenyun** [linkedin/naarad#309]
After checking out naarad, then run a sample, it complains:    ImportError: No module named luminol

// I need to uncomment the line in naarad/src/naarad/metrics/metric.py
#from luminol import anomaly_detector, correlator

**Comment by richardhsu** [comment]
Okay, maybe we should update so that luminol is installed as a dependency then rather than commenting it out or doing try/catch around the import.

**Comment by RiteshMaheshwari** [comment]
Just to clarify, luminol is integrated with naarad. See https://github.com/linkedin/naarad/blob/master/src/naarad/utils.py#L757

Its controlled through config.

**Comment by RiteshMaheshwari** [comment]
@richardhsu , do you know how to add it as dependency? Otherwise adding a try except block is an easy quick fix.

**Comment by richardhsu** [comment]
I think the best approach is to place Luminol in the requirements or in setup for Naarad, we include the installation of Luminol since the source code is packaged with Naarad.

**Comment by richardhsu** [comment]
It looks like Luminol is already included in the requirements. I think Zen just needs to have luminol installed. Anyone moving forward and installing from `master` should get the correct dependencies.

@zhenyun can you rerun `pip install -r requirements.txt` to get Luminol and you won't have to worry about the import.

**Comment by zhenyun** [comment]
That is right. 
close it.
