### ISSUE TITLE
Naarad cannot import graphing library None on your system. Will not generate static charts

### ISSUE THREAD

**Issue by arpras** [linkedin/naarad#331]
Zopkio is another souce project where we include naarad for performance analysis. I believe I have installed all the graphic libraries as mentioned in naarad's requirement.txt including matplotlib.
Can you tell me if there is something missing ?

To repro: 
git clone https://github.com/linkedin/Zopkio.git
python setup.py install
zopkio examples/server_client/server_client.py

**Comment by RiteshMaheshwari** [comment]
@arpras ,

What do you see logged for this statement?

"Available graphing modules:"

**Comment by richardhsu** [comment]
Log states that `matplotlib` is available but then Naarad is reporting that it cannot import graphing module `None`. Working with him right now on issue.

**Comment by richardhsu** [comment]
Determined that 1.0.8 naarad in pypi has the bug and needs the following commit: 6ea0d568d6e0e

**Comment by arpras** [comment]
Thanks for resolving this.

**Comment by richardhsu** [comment]
This is fixed in the latest PyPi package of v1.0.14 which can be installed with `pip install naarad` now as the latest version!

Thanks @arpras for reporting this issue!
