### ISSUE TITLE
DataThroughput and QPS are miscalculated in JMETER Summary page

### ISSUE THREAD

**Issue by JingshuXia** [linkedin/naarad#338]
Used Naarad to parse a Jmeter test raw log, the test ran for 4.8 req/s from Jmeter terminal output, but Naarad parsed it as 181 in overral.summary.qps and the mean dataThroughput is calculated as 6. 
Using ApacheJmeter 2.13, screenshots are attached. 
Jmeter output:
<img width="1028" alt="screen shot 2015-08-17 at 4 36 45 pm" src="https://cloud.githubusercontent.com/assets/406665/9318983/37242474-44fe-11e5-9390-5efe7239390a.png">
Naarad report:
<img width="1162" alt="screen shot 2015-08-17 at 4 39 10 pm" src="https://cloud.githubusercontent.com/assets/406665/9319013/8410c81e-44fe-11e5-9808-30681e10f29b.png">

**Comment by RiteshMaheshwari** [comment]
Looks like a longer run with aggregation at second level makes the data very close. So closing this now.
