### ISSUE TITLE
Incorrect bin path when installed with Virtualenv

### ISSUE THREAD

**Issue by kilink** [linkedin/naarad#345]
After installing naarad in a virtualenv envrironment, running the bin/naarad script silently fails when it attempts to execute PrintGCStats.

Directory layout in virtualenv:

scripts:
bin/naarad
bin/PrintGCStats

actual naarad package:
lib/python2.7/site-packages/naarad/

Where naarad thinks PrintGCStats is located:
lib/python2.7/bin/PrintGCStats

The problem is due to the line in [naarad.utils](https://github.com/linkedin/naarad/blob/665f58f76c2412e125f2be2c111ebc7cdf6ff92e/src/naarad/utils.py#L949) where the bin_path is set based on the path of the naarad.utils module.

This path should probably be determined based on the naarad script in bin/naarad itself, since that is the execution entry point.

Note that this would also be an issue with other Python package tools such as Buildout.

**Comment by RiteshMaheshwari** [comment]
@kilink Thanks for the bug report! Any chance you can submit a pull request that we can review/merge?

**Comment by zhenyun** [comment]
It seems __init__.py (under naarad) also has one of such issue: 
 new_metric.bin_path = os.path.abspath(os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))), 'bin'))

**Comment by zhenyun** [comment]
@kilink , I think your changes work; 
Would you like to change the _ _ init _ _.py also so that we can merge? 
Thanks.
